import type { CompanyEnriched, Contact, Signal } from "./types";

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

// ---------------------------------------------------------------------------
// 5 realistic demo companies for first-load experience
// ---------------------------------------------------------------------------

const seedSignals: Signal[] = [
  {
    id: "seed-s1",
    companyDomain: "techflowsolutions.example.com",
    type: "hiring",
    title: "TechFlow hiring VP of Engineering",
    description: "New leadership role for cloud infrastructure team expansion.",
    date: daysAgo(3),
    sourceUrl: null,
    source: "exa",
  },
  {
    id: "seed-s2",
    companyDomain: "techflowsolutions.example.com",
    type: "funding",
    title: "TechFlow raises $45M Series C",
    description: "Funding led by Sequoia to accelerate enterprise SaaS growth.",
    date: daysAgo(8),
    sourceUrl: null,
    source: "exa",
  },
  {
    id: "seed-s3",
    companyDomain: "greenleafingredients.example.com",
    type: "expansion",
    title: "GreenLeaf opens new plant in Singapore",
    description: "$80M investment in specialty food ingredients manufacturing for APAC.",
    date: daysAgo(5),
    sourceUrl: null,
    source: "exa",
  },
  {
    id: "seed-s4",
    companyDomain: "nordicmanufacturing.example.com",
    type: "hiring",
    title: "Nordic Manufacturing recruiting sustainability lead",
    description: "New role to drive ESG compliance across European operations.",
    date: daysAgo(2),
    sourceUrl: null,
    source: "apollo",
  },
  {
    id: "seed-s5",
    companyDomain: "meridianpharma.example.com",
    type: "funding",
    title: "Meridian secures $120M for biosimilar pipeline",
    description: "Major investment to accelerate Phase III clinical trials.",
    date: daysAgo(6),
    sourceUrl: null,
    source: "exa",
  },
  {
    id: "seed-s6",
    companyDomain: "meridianpharma.example.com",
    type: "expansion",
    title: "Meridian expands to Latin America",
    description: "New distribution partnerships in Brazil and Mexico.",
    date: daysAgo(12),
    sourceUrl: null,
    source: "exa",
  },
  {
    id: "seed-s7",
    companyDomain: "atlaspackaging.example.com",
    type: "hiring",
    title: "Atlas Packaging scaling engineering team",
    description: "25+ packaging engineers needed for sustainable materials division.",
    date: daysAgo(4),
    sourceUrl: null,
    source: "apollo",
  },
];

export const SEED_CONTACTS: Record<string, Contact[]> = {
  "techflowsolutions.example.com": [
    {
      id: "seed-ct1",
      companyDomain: "techflowsolutions.example.com",
      companyName: "TechFlow Solutions",
      firstName: "Priya",
      lastName: "Mehta",
      title: "Chief Technology Officer",
      email: "pmehta@example.com",
      phone: "+1-415-555-0110",
      linkedinUrl: "https://linkedin.com/in/priyamehta",
      emailConfidence: 94,
      confidenceLevel: "high",
      sources: ["apollo", "exa"],
      seniority: "c_level",
      lastVerified: daysAgo(1),
    },
    {
      id: "seed-ct2",
      companyDomain: "techflowsolutions.example.com",
      companyName: "TechFlow Solutions",
      firstName: "James",
      lastName: "Okonkwo",
      title: "VP of Sales",
      email: "jokonkwo@example.com",
      phone: null,
      linkedinUrl: "https://linkedin.com/in/jamesokonkwo",
      emailConfidence: 87,
      confidenceLevel: "medium",
      sources: ["apollo"],
      seniority: "vp",
      lastVerified: daysAgo(4),
    },
    {
      id: "seed-ct3",
      companyDomain: "techflowsolutions.example.com",
      companyName: "TechFlow Solutions",
      firstName: "Elena",
      lastName: "Vasquez",
      title: "Director of Partnerships",
      email: "evasquez@example.com",
      phone: null,
      linkedinUrl: null,
      emailConfidence: 78,
      confidenceLevel: "medium",
      sources: ["exa"],
      seniority: "director",
      lastVerified: daysAgo(7),
    },
  ],
  "greenleafingredients.example.com": [
    {
      id: "seed-ct4",
      companyDomain: "greenleafingredients.example.com",
      companyName: "GreenLeaf Ingredients",
      firstName: "Hans",
      lastName: "Richter",
      title: "Chief Procurement Officer",
      email: "hrichter@example.com",
      phone: "+49-30-555-0200",
      linkedinUrl: "https://linkedin.com/in/hansrichter",
      emailConfidence: 91,
      confidenceLevel: "high",
      sources: ["apollo", "hubspot"],
      seniority: "c_level",
      lastVerified: daysAgo(2),
    },
    {
      id: "seed-ct5",
      companyDomain: "greenleafingredients.example.com",
      companyName: "GreenLeaf Ingredients",
      firstName: "Mei",
      lastName: "Chen",
      title: "VP of Innovation",
      email: "mchen@example.com",
      phone: null,
      linkedinUrl: "https://linkedin.com/in/meichen",
      emailConfidence: 85,
      confidenceLevel: "medium",
      sources: ["apollo"],
      seniority: "vp",
      lastVerified: daysAgo(5),
    },
  ],
  "nordicmanufacturing.example.com": [
    {
      id: "seed-ct6",
      companyDomain: "nordicmanufacturing.example.com",
      companyName: "Nordic Manufacturing Co",
      firstName: "Lars",
      lastName: "Eriksson",
      title: "Managing Director",
      email: "leriksson@example.com",
      phone: "+46-8-555-0300",
      linkedinUrl: "https://linkedin.com/in/larseriksson",
      emailConfidence: 92,
      confidenceLevel: "high",
      sources: ["apollo", "exa"],
      seniority: "c_level",
      lastVerified: daysAgo(1),
    },
    {
      id: "seed-ct7",
      companyDomain: "nordicmanufacturing.example.com",
      companyName: "Nordic Manufacturing Co",
      firstName: "Astrid",
      lastName: "Nygaard",
      title: "Director of Supply Chain",
      email: "anygaard@example.com",
      phone: null,
      linkedinUrl: null,
      emailConfidence: 74,
      confidenceLevel: "medium",
      sources: ["apollo"],
      seniority: "director",
      lastVerified: daysAgo(10),
    },
  ],
  "meridianpharma.example.com": [
    {
      id: "seed-ct8",
      companyDomain: "meridianpharma.example.com",
      companyName: "Meridian Pharma Group",
      firstName: "Anil",
      lastName: "Kapoor",
      title: "CEO",
      email: "akapoor@example.com",
      phone: "+91-22-555-0400",
      linkedinUrl: "https://linkedin.com/in/anilkapoor",
      emailConfidence: 96,
      confidenceLevel: "high",
      sources: ["apollo", "hubspot", "exa"],
      seniority: "c_level",
      lastVerified: daysAgo(0),
    },
    {
      id: "seed-ct9",
      companyDomain: "meridianpharma.example.com",
      companyName: "Meridian Pharma Group",
      firstName: "Sofia",
      lastName: "Rodriguez",
      title: "VP of Business Development",
      email: "srodriguez@example.com",
      phone: null,
      linkedinUrl: "https://linkedin.com/in/sofiarodriguez",
      emailConfidence: 82,
      confidenceLevel: "medium",
      sources: ["apollo"],
      seniority: "vp",
      lastVerified: daysAgo(6),
    },
    {
      id: "seed-ct10",
      companyDomain: "meridianpharma.example.com",
      companyName: "Meridian Pharma Group",
      firstName: "Tomoko",
      lastName: "Tanaka",
      title: "Director of Regulatory Affairs",
      email: "ttanaka@example.com",
      phone: null,
      linkedinUrl: null,
      emailConfidence: 70,
      confidenceLevel: "medium",
      sources: ["exa"],
      seniority: "director",
      lastVerified: daysAgo(14),
    },
  ],
  "atlaspackaging.example.com": [
    {
      id: "seed-ct11",
      companyDomain: "atlaspackaging.example.com",
      companyName: "Atlas Packaging Solutions",
      firstName: "Michael",
      lastName: "Brooks",
      title: "Chief Commercial Officer",
      email: "mbrooks@example.com",
      phone: "+1-312-555-0500",
      linkedinUrl: "https://linkedin.com/in/michaelbrooks",
      emailConfidence: 89,
      confidenceLevel: "medium",
      sources: ["apollo", "hubspot"],
      seniority: "c_level",
      lastVerified: daysAgo(3),
    },
    {
      id: "seed-ct12",
      companyDomain: "atlaspackaging.example.com",
      companyName: "Atlas Packaging Solutions",
      firstName: "Fatima",
      lastName: "Al-Hassan",
      title: "Director of Sustainability",
      email: "falhassan@example.com",
      phone: null,
      linkedinUrl: "https://linkedin.com/in/fatimaalhassan",
      emailConfidence: 76,
      confidenceLevel: "medium",
      sources: ["exa"],
      seniority: "director",
      lastVerified: daysAgo(9),
    },
  ],
};

export const SEED_COMPANIES: CompanyEnriched[] = [
  {
    domain: "techflowsolutions.example.com",
    name: "TechFlow Solutions",
    firstViewedBy: "Demo",
    firstViewedAt: daysAgo(0),
    lastViewedBy: "Demo",
    lastViewedAt: daysAgo(0),
    source: "exa",
    noteCount: 0,
    lastNoteAt: null,
    extractionCount: 0,
    lastExtractionAt: null,
    excluded: false,
    excludedBy: null,
    excludedAt: null,
    exclusionReason: null,
    status: "new",
    statusChangedBy: null,
    statusChangedAt: null,
    viewedBy: null,
    industry: "Enterprise SaaS",
    vertical: "Technology",
    employeeCount: 340,
    location: "San Francisco, CA",
    region: "North America",
    description: "Cloud-native workflow automation platform for mid-market enterprises. Specializes in no-code integration and process mining.",
    icpScore: 85,
    hubspotStatus: "none",
    freshsalesStatus: "none",
    freshsalesIntel: null,
    sources: ["exa", "apollo"],
    signals: seedSignals.filter((s) => s.companyDomain === "techflowsolutions.example.com"),
    contactCount: 3,
    lastRefreshed: daysAgo(0),
    revenue: "$42M",
    founded: "2019",
  },
  {
    domain: "greenleafingredients.example.com",
    name: "GreenLeaf Ingredients",
    firstViewedBy: "Demo",
    firstViewedAt: daysAgo(0),
    lastViewedBy: "Demo",
    lastViewedAt: daysAgo(0),
    source: "exa",
    noteCount: 0,
    lastNoteAt: null,
    extractionCount: 0,
    lastExtractionAt: null,
    excluded: false,
    excludedBy: null,
    excludedAt: null,
    exclusionReason: null,
    status: "new",
    statusChangedBy: null,
    statusChangedAt: null,
    viewedBy: null,
    industry: "Food Ingredients",
    vertical: "Food Ingredients",
    employeeCount: 1800,
    location: "Amsterdam, Netherlands",
    region: "Europe",
    description: "Sustainable plant-based ingredient solutions for the food and beverage industry. Strong focus on clean-label products and APAC expansion.",
    icpScore: 78,
    hubspotStatus: "open",
    freshsalesStatus: "none",
    freshsalesIntel: null,
    sources: ["exa", "apollo"],
    signals: seedSignals.filter((s) => s.companyDomain === "greenleafingredients.example.com"),
    contactCount: 2,
    lastRefreshed: daysAgo(1),
    revenue: "$320M",
    founded: "2005",
  },
  {
    domain: "nordicmanufacturing.example.com",
    name: "Nordic Manufacturing Co",
    firstViewedBy: "Demo",
    firstViewedAt: daysAgo(0),
    lastViewedBy: "Demo",
    lastViewedAt: daysAgo(0),
    source: "apollo",
    noteCount: 0,
    lastNoteAt: null,
    extractionCount: 0,
    lastExtractionAt: null,
    excluded: false,
    excludedBy: null,
    excludedAt: null,
    exclusionReason: null,
    status: "new",
    statusChangedBy: null,
    statusChangedAt: null,
    viewedBy: null,
    industry: "Industrial Manufacturing",
    vertical: "Chemicals",
    employeeCount: 5200,
    location: "Stockholm, Sweden",
    region: "Europe",
    description: "Specialty chemicals and advanced materials manufacturer serving automotive, electronics, and energy sectors across Northern Europe.",
    icpScore: 62,
    hubspotStatus: "none",
    freshsalesStatus: "none",
    freshsalesIntel: null,
    sources: ["apollo"],
    signals: seedSignals.filter((s) => s.companyDomain === "nordicmanufacturing.example.com"),
    contactCount: 2,
    lastRefreshed: daysAgo(2),
    revenue: "$890M",
    founded: "1987",
  },
  {
    domain: "meridianpharma.example.com",
    name: "Meridian Pharma Group",
    firstViewedBy: "Demo",
    firstViewedAt: daysAgo(0),
    lastViewedBy: "Demo",
    lastViewedAt: daysAgo(0),
    source: "exa",
    noteCount: 0,
    lastNoteAt: null,
    extractionCount: 0,
    lastExtractionAt: null,
    excluded: false,
    excludedBy: null,
    excludedAt: null,
    exclusionReason: null,
    status: "new",
    statusChangedBy: null,
    statusChangedAt: null,
    viewedBy: null,
    industry: "Pharmaceuticals",
    vertical: "Pharma",
    employeeCount: 8500,
    location: "Mumbai, India",
    region: "Asia Pacific",
    description: "Integrated pharmaceutical company with a growing biosimilar pipeline. Expanding distribution across Latin America and Southeast Asia.",
    icpScore: 71,
    hubspotStatus: "in_progress",
    freshsalesStatus: "none",
    freshsalesIntel: null,
    sources: ["exa", "apollo"],
    signals: seedSignals.filter((s) => s.companyDomain === "meridianpharma.example.com"),
    contactCount: 3,
    lastRefreshed: daysAgo(0),
    revenue: "$1.2B",
    founded: "1996",
  },
  {
    domain: "atlaspackaging.example.com",
    name: "Atlas Packaging Solutions",
    firstViewedBy: "Demo",
    firstViewedAt: daysAgo(0),
    lastViewedBy: "Demo",
    lastViewedAt: daysAgo(0),
    source: "exa",
    noteCount: 0,
    lastNoteAt: null,
    extractionCount: 0,
    lastExtractionAt: null,
    excluded: false,
    excludedBy: null,
    excludedAt: null,
    exclusionReason: null,
    status: "new",
    statusChangedBy: null,
    statusChangedAt: null,
    viewedBy: null,
    industry: "Packaging",
    vertical: "Packaging",
    employeeCount: 3200,
    location: "Chicago, IL",
    region: "North America",
    description: "Sustainable packaging solutions for food, beverage, and consumer goods. Leading the shift to recyclable and compostable materials.",
    icpScore: 35,
    hubspotStatus: "none",
    freshsalesStatus: "none",
    freshsalesIntel: null,
    sources: ["exa"],
    signals: seedSignals.filter((s) => s.companyDomain === "atlaspackaging.example.com"),
    contactCount: 2,
    lastRefreshed: daysAgo(3),
    revenue: "$580M",
    founded: "2001",
  },
];
